PRAGMA foreign_keys=ON;
CREATE TABLE viewing_slots(id TEXT PRIMARY KEY,property_id TEXT NOT NULL REFERENCES properties(id),start_at TEXT NOT NULL,end_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('available','held','confirmed','closed')),created_by_user_id TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE viewing_requests(id TEXT PRIMARY KEY,reference_code TEXT NOT NULL UNIQUE,property_id TEXT NOT NULL REFERENCES properties(id),viewing_slot_id TEXT NOT NULL REFERENCES viewing_slots(id),requester_user_id TEXT NOT NULL REFERENCES users(id),phone_snapshot TEXT NOT NULL,party_size INTEGER NOT NULL CHECK(party_size BETWEEN 1 AND 10),note TEXT,status TEXT NOT NULL CHECK(status IN('pending','confirmed','cancelled','completed')),confirmation_deadline_at TEXT NOT NULL,contact_name TEXT,contact_method TEXT,meeting_location TEXT,meeting_instructions TEXT,cancellation_reason TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX one_active_request_per_slot ON viewing_requests(viewing_slot_id) WHERE status IN('pending','confirmed');
CREATE TABLE viewing_status_events(id TEXT PRIMARY KEY,viewing_request_id TEXT NOT NULL REFERENCES viewing_requests(id),from_status TEXT,to_status TEXT NOT NULL,actor_user_id TEXT REFERENCES users(id),reason TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE viewing_meeting_detail_events(id TEXT PRIMARY KEY,viewing_request_id TEXT NOT NULL REFERENCES viewing_requests(id),changed_by_user_id TEXT NOT NULL REFERENCES users(id),new_values_json TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE notifications(id TEXT PRIMARY KEY,recipient_user_id TEXT NOT NULL REFERENCES users(id),type TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,read_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE email_deliveries(id TEXT PRIMARY KEY,notification_id TEXT REFERENCES notifications(id),recipient_email_snapshot TEXT NOT NULL,template_key TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('queued','sent','failed')),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,sent_at TEXT,failed_at TEXT);
INSERT OR REPLACE INTO users(id,email_normalized,password_hash,email_verified_at,identity_verified_at,role,can_review_documents) VALUES
('user-tenant-test','tenant@example.test','pbkdf2-sha256$210000$tenant00000000000000000000000000$55566330f7ab34125f14cbe45bfc34163f0944164c10f6fe21896d0fee439f25',CURRENT_TIMESTAMP,NULL,'member',0),
('user-verified-test','verified@example.test','pbkdf2-sha256$210000$verified0000000000000000000000$6aee71e2e6bc8ac74327a88c9f9d27b1f76057bc5de9987379c4fb6d0126bd81',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'member',0),
('user-landlord-test','landlord@example.test','pbkdf2-sha256$210000$landlord0000000000000000000000$91b961afe155dc32e9bafd9e5e8d12091557d1733d03bbf51f765512e487acb2',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'member',0),
('user-admin-test','admin@example.test','pbkdf2-sha256$210000$admin000000000000000000000000$56fab8021087b8e1fa22ebf400a46579dc2c599f78544a35ebcfc49a365a5367',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'admin',1);
INSERT OR REPLACE INTO profiles(user_id,display_name,legal_name) VALUES ('user-tenant-test','一般租客','一般租客'),('user-verified-test','驗證租客','驗證租客'),('user-landlord-test','示範房東','示範房東'),('user-admin-test','管理員','管理員');
UPDATE properties SET provider_user_id='user-admin-test',viewing_requirement='identity_verified' WHERE id='property-demo-001';
INSERT OR IGNORE INTO viewing_slots(id,property_id,start_at,end_at,status,created_by_user_id) VALUES ('slot-db-01','property-demo-001','2026-07-20T10:00:00+08:00','2026-07-20T11:00:00+08:00','available','user-admin-test'),('slot-db-02','property-demo-001','2026-07-20T14:00:00+08:00','2026-07-20T15:00:00+08:00','available','user-admin-test');
